name: learn2
on: 
 push:
    branches:
      - production

env:
  ASERVER: production

defaults:
  run:
    shell: bash
    working-directory: /home/andy.pranata/aaa/

jobs:
  testrun2:
    runs-on: cayalinux
    steps:
      - run: uptime
      - run: echo $ASERVER > ./test