name: learn3
on: 
 push:
    branches:
      - production

env:
  ASERVER: production

defaults:
  run:
    working-directory: /home/andy.pranata/aaa/

jobs:
  testrun3:
    runs-on: cayalinux
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1